# Python Insights - Analisando Dados com Python

### Case - Cancelamento de Clientes

Você foi contratado por uma empresa com mais de 800 mil clientes para um projeto de Dados. Recentemente a empresa percebeu que da sua base total de clientes, a maioria são clientes inativos, ou seja, que já cancelaram o serviço.

Precisando melhorar seus resultados ela quer conseguir entender os principais motivos desses cancelamentos e quais as ações mais eficientes para reduzir esse número.

Base de dados e arquivos: https://drive.google.com/drive/folders/1uDesZePdkhiraJmiyeZ-w5tfc8XsNYFZ?usp=drive_link

In [37]:
#Passo a passo do projeto 

#Passo 1: Abrir a base de dados (Importar a base de dados)
import pandas as pd #pacote para importar a base de dados (o "as pd" serve para colocar um apelido no pandas para não usar "pandas" toda vez de escrever)

tabela = pd.read_csv("cancelamentos.csv")   #armazena o arquico na variavel tabela 
display(tabela) #enves de usar o print, pode usar o display(que deixa a tabela mais visual)

#kaggle (site com varias base de dados para treinar)

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,349936.0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,100634.0,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,301263.0,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,119358.0,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,130955.0,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,195680.0,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,43477.0,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,169273.0,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,310693.0,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,251915.0,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

In [38]:
#Passo 2: Vizualizar a base de dados 
    #Entender as informações disponiveis 
    #Possiveis prblemas/erros na base de dados 

#informações que não te ajudam te atrapalham 
#o ID do consumidor, NESSE CASO não serve para nada na analise
tabela = pd.read_csv("cancelamentos.csv")

tabela = tabela.drop(columns="CustomerID")  #remove a coluna CustomerID
display(tabela)

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
49995,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

In [39]:
#Passo 3: Corrigir os problemas da base de dados (Tratamento de dados)
#Valores em formatos errados
#Informações vazias 

display(tabela.info())  #mostra as informações da tabela (a partir disso, excluir linhas que possuem informações vazias)

tabela = tabela.dropna()    #na = vazio = NaN - Not a Namber
display(tabela.info())

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   idade                   50000 non-null  float64
 1   sexo                    49997 non-null  str
 2   tempo_como_cliente      49998 non-null  float64
 3   frequencia_uso          50000 non-null  float64
 4   ligacoes_callcenter     50000 non-null  float64
 5   dias_atraso             50000 non-null  float64
 6   assinatura              50000 non-null  str
 7   duracao_contrato        50000 non-null  str
 8   total_gasto             50000 non-null  float64
 9   meses_ultima_interacao  50000 non-null  float64
 10  cancelou                50000 non-null  float64
dtypes: float64(8), str(3)
memory usage: 4.2 MB

None

<class 'pandas.DataFrame'>
Index: 49996 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   idade                   49996 non-null  float64
 1   sexo                    49996 non-null  str
 2   tempo_como_cliente      49996 non-null  float64
 3   frequencia_uso          49996 non-null  float64
 4   ligacoes_callcenter     49996 non-null  float64
 5   dias_atraso             49996 non-null  float64
 6   assinatura              49996 non-null  str
 7   duracao_contrato        49996 non-null  str
 8   total_gasto             49996 non-null  float64
 9   meses_ultima_interacao  49996 non-null  float64
 10  cancelou                49996 non-null  float64
dtypes: float64(8), str(3)
memory usage: 4.6 MB

None

In [40]:
#Passo 4: Analise inicial (entender quantos clientes cancelaram)
#Antes de fazer a analise, é bom saber quantos clientes cancelaram(pra verificar se é necessario uma mudança)
#cancelou = 0 NÃO CANCELOU, cancelou = 1 CANCELOU   

print(tabela["cancelou"].value_counts())   #contar valores

print(tabela["cancelou"].value_counts(normalize=True))  #dizer o percentual

cancelou
1.0    28393
0.0    21603
Name: count, dtype: int64
cancelou
1.0    0.567905
0.0    0.432095
Name: proportion, dtype: float64

In [41]:
#Passo 5: Analise detalhads (entender o porque de cada cliente cancelou/como cadas coluna impacta no cancelamento)
#Usar grafico para ser melhor de analisar e apresentar(USAR GRAFICOS INTUITIVOS)    
import plotly.express as px #px é só para apelido 


for coluna in tabela.columns:   #para cada coluna dentro tabela 
    #cria grafico
    grafico = px.histogram(tabela, x=coluna, color="cancelou",text_auto=True)  #diferencia quem cancelou e quem não cancelou na duração de contrato
    grafico.show()  #exibe

In [42]:
#CONCLUSÕES 

#TODOS DA CATEGORIA MENSAL CANCELARAM   
    #vamos dar desconto no contrato anual/trimestral para mudarem de contrato

#Se o cliente liga mais de 4 vezes pro callcenter ele cancela
    #ou seja, TEM ALGUM PROBLEMA SEM SOLUÇÃO 
    #Se ele ligar 3x, ligar um alerta especifico para o cliente 

#Se o cliente atrasa 20 dias de pagamento ele cancela
    #criar uma politica(se o cliente atrasar 15 dias, entrar em contato e tentar renegociar)

#filtrar a base de dados 
#duracao_contrato
    #duracao_contrato -> diferente de Monthly
condicao = tabela["duracao_contrato"] != "Monthly"  #Se resolver o problema de cancelamento mensal como fica a media de cancelamento
tabela = tabela[condicao]

#ligacoes_callcenter 
    #menores de 4 vezes 
condicao = tabela["ligacoes_callcenter"] <= 4
tabela = tabela[condicao]

#dias_atraso
    #maximo 15 dias
condicao = tabela["dias_atraso"] <= 20
tabela = tabela[condicao]

#porcentagem 
display(tabela["cancelou"].value_counts(normalize=True))    #porcentagem de cancelamento se resolver os tres problemas

cancelou
0.0    0.816462
1.0    0.183538
Name: proportion, dtype: float64